package de.memorian.gzg.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF256c2c)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFa9f5a4)
val md_theme_light_onPrimaryContainer = Color(0xFF082009)
val md_theme_light_secondary = Color(0xFF266c2b)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFaaf5a4)
val md_theme_light_onSecondaryContainer = Color(0xFF082009)
val md_theme_light_tertiary = Color(0xFF38656a)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbdebf1)
val md_theme_light_onTertiaryContainer = Color(0xFF001f23)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfdf6)
val md_theme_light_onBackground = Color(0xFF1a1c19)
val md_theme_light_surface = Color(0xFFfcfdf6)
val md_theme_light_onSurface = Color(0xFF1a1c19)
val md_theme_light_surfaceVariant = Color(0xFFdee5d8)
val md_theme_light_onSurfaceVariant = Color(0xFF424840)
val md_theme_light_outline = Color(0xFF72796f)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1eb)
val md_theme_light_inverseSurface = Color(0xFF2f312d)

val md_theme_dark_primary = Color(0xFF8ed88b)
val md_theme_dark_onPrimary = Color(0xFF003908)
val md_theme_dark_primaryContainer = Color(0xFF035316)
val md_theme_dark_onPrimaryContainer = Color(0xFFa9f5a4)
val md_theme_dark_secondary = Color(0xFF8fd88a)
val md_theme_dark_onSecondary = Color(0xFF003907)
val md_theme_dark_secondaryContainer = Color(0xFF045315)
val md_theme_dark_onSecondaryContainer = Color(0xFFaaf5a4)
val md_theme_dark_tertiary = Color(0xFFa1cfd5)
val md_theme_dark_onTertiary = Color(0xFF00363b)
val md_theme_dark_tertiaryContainer = Color(0xFF1e4d52)
val md_theme_dark_onTertiaryContainer = Color(0xFFbdebf1)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c19)
val md_theme_dark_onBackground = Color(0xFFe2e3dd)
val md_theme_dark_surface = Color(0xFF1a1c19)
val md_theme_dark_onSurface = Color(0xFFe2e3dd)
val md_theme_dark_surfaceVariant = Color(0xFF424840)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c9bd)
val md_theme_dark_outline = Color(0xFF8c9388)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c19)
val md_theme_dark_inverseSurface = Color(0xFFe2e3dd)

val seed = Color(0xFF8bcc87)
val error = Color(0xFFba1b1b)